config/routes.rb
Puppet::Application.routes.draw do |map|
  resources :cities, :only => [:new, :create, :show, :index] do
    member do
      post :manage
    end
  end

  get "home/index"

  devise_for :users

  root :to => "home#index"

end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :city

  validates_presence_of :name, :city
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"
  has_many :buildings

  attr_accessible :name

  validates_presence_of :name, :owner

  before_create :set_defaults
  before_save :limit_population_by_capacity

  def is_full?
    self.population == total_capacity
  end

  def total_capacity
    self.buildings.to_a.sum(&:capacity)
  end

  private
  def set_defaults
    self.total_space = 9 unless self.total_space
    self.free_space = 9 unless self.free_space
    self.budget = 1000 unless self.budget
    self.population = 0 unless self.population
  end

  def limit_population_by_capacity
    self.population = [population, total_capacity].min
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

  has_many :cities, :foreign_key => :owner_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def require_user
    unless current_user
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_filter :require_user
  before_filter :retrieve_city, :only => [:show, :manage]

  def new
    @city = current_user.cities.new
  end

  def create
    @city = current_user.cities.create(params[:city])
    if @city.save
      redirect_to cities_path
    else
      render :new
    end
  end

  def show
  end

  def index
    @cities = current_user.cities
  end

  def manage
    begin
      command = CityCommands.handle!(params[:command], :city => @city)
      flash[:notice] = command.message
    rescue UserActionError => error
      flash[:alert] = error.message
    end
    redirect_to city_path(@city)
  end

  private
    def retrieve_city
      @city = current_user.cities.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to(cities_path) if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
  def city_space_summary(city)
    "#{city.free_space} / #{city.total_space}"
  end

  def city_population_summary(city)
    "#{city.population} / #{city.total_capacity}"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cities/index.html.haml
%h1 Your cities

- if @cities.empty?
  %p
    This is a game about building a city. Please use the link below to create your first city.
- else
  %table
    %tr
      %th Name
      %th Budget
      %th Population
      %th Space
      %th Action
    - for city in @cities
      %tr
        %td= city.name
        %td= city.budget
        %td= city_population_summary(city)
        %td= city_space_summary(city)
        %td= link_to "Visit", city_path(city)

%p= link_to "Create new city", new_city_path

app/views/cities/new.html.haml
%p
  Give your city a name first.

= form_for @city do |f|
  = f.label :name, "Name"
  = f.error_message_on :name
  = f.text_field :name
  = f.submit "Create"

app/views/cities/show.html.haml
%h1= @city.name

%p
  You can increase population by building houses. More people mean more money over time (through taxes).

%h3 Information
%dl
  %dt Population / capacity
  %dd= city_population_summary(@city)
  %dt Budget
  %dd= @city.budget
  %dt Free space / total space
  %dd= city_space_summary(@city)

%h3 Buildings
%ul
  - for building in @city.buildings
    %li= building.name

%h3 Actions
- for command in CityCommands.all
  - if command.available?(:city => @city)
    = form_tag manage_city_path(@city) do
      = hidden_field_tag "command", command.name
      = submit_tag command.label.capitalize
  - else
    = "You can't #{command.label} at the moment."
    %ul
      - for reason in command.unavailability_reasons(:city => @city)
        %li= reason

app/views/home/index.html.haml
%h1
  Welcome to puppet!

%p
  Please use the navigation link above to register. You have to register to begin playing.

app/views/layouts/_navigation.html.haml
- if user_signed_in?
  = "You are logged in as #{current_user.email}"
  = link_to "Your cities", cities_path
  = link_to "Logout", destroy_user_session_path
- else
  = link_to "Login", new_user_session_path
  = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!! Strict
%html{:xmlns => 'http://www.w3.org/1999/xhtml', 'xml:lang' => 'en', :lang => 'en'}
  %head
    %meta{"http-equiv" => "Content-Type", "content" => "text/html;charset=utf-8"}/
    %title Puppet
    = stylesheet_link_tag :all
    = csrf_meta_tag
  %body
    %p.navigation= render 'layouts/navigation'
    %p.notice= notice
    %p.alert= alert
    = yield